"""
CoachPosition Model
- _id: ObjectId (automatically generated by MongoDB)
- train_id: ObjectId (reference to Train)
- coach_number: String (coach identifier)
- platform_number: String (platform at station)
- position_on_platform: String (e.g., 'front', 'middle', 'rear', or meter offset)
- station: String (station name or code)
- eta: String (estimated time of arrival at this station)
- updated_at: DateTime
"""

"""
Quota Model
- _id: ObjectId (automatically generated by MongoDB)
- train_id: ObjectId (reference to Train)
- coach_number: String (coach identifier)
- quota_type: String (general, tatkal, ladies, etc.)
- total_seats: Integer
- available_seats: Integer
- updated_at: DateTime
"""
# This file defines the data models for our MongoDB collections
# Since MongoDB is schema-less, these are not strict models but serve as documentation
# and validation reference for our application

"""
User Model
- _id: ObjectId (automatically generated by MongoDB)
- name: String (user's full name)
- email: String (user's email address, unique)
- password: String (hashed password in production)
- role: String (passenger, admin, staff)
- created_at: DateTime
"""

"""
Train Model
- _id: ObjectId (automatically generated by MongoDB)
- name: String (train name/number)
- source: String (departure station)
- destination: String (arrival station)
- departure_time: String (time of departure)
- arrival_time: String (time of arrival)
- total_seats: Integer (total number of seats)
- available_seats: Integer (number of available seats)
- status: String (scheduled, delayed, cancelled, completed)
- created_at: DateTime
"""

"""
Booking Model
- _id: ObjectId (automatically generated by MongoDB)
- user_id: ObjectId (reference to User)
- train_id: ObjectId (reference to Train)
- train_name: String (name of the train)
- seats: Array (list of seat numbers)
- date: String (date of journey)
- status: String (confirmed, cancelled, completed)
- created_at: DateTime
"""

"""
Tracking Model
- _id: ObjectId (automatically generated by MongoDB)
- train_id: ObjectId (reference to Train)
- current_location: String (current station or coordinates)
- next_station: String (next station)
- estimated_arrival: String (estimated arrival time at next station)
- status: String (on-time, delayed, etc.)
- delay_minutes: Integer (if delayed, minutes of delay)
- updated_at: DateTime
"""

"""
Alert Model
- _id: ObjectId (automatically generated by MongoDB)
- message: String (alert message)
- type: String (delay, cancellation, platform_change, emergency, etc.)
- train_id: ObjectId (reference to Train, optional)
- created_at: DateTime
"""

"""
Coach Model
- _id: ObjectId (automatically generated by MongoDB)
- train_id: ObjectId (reference to Train)
- coach_number: String (coach identifier)
- coach_type: String (sleeper, AC, general, etc.)
- total_seats: Integer (total seats in this coach)
- available_seats: Integer (available seats in this coach)
- seat_map: Object (mapping of seat numbers to availability)
"""

"""
Payment Model
- _id: ObjectId (automatically generated by MongoDB)
- booking_id: ObjectId (reference to Booking)
- user_id: ObjectId (reference to User)
- amount: Float (payment amount)
- payment_method: String (credit card, debit card, UPI, etc.)
- transaction_id: String (payment gateway transaction ID)
- status: String (pending, completed, failed, refunded)
- created_at: DateTime
"""